config/routes.rb
Rails.application.routes.draw do
  resources :priest_users

  resources :areas
  resources :cities

 root 'welcome#index'
 get 'welcome/ada'
 

end

app/models/area.rb
class Area < ActiveRecord::Base
	belongs_to :city
	has_many :priest_users

	scope :cityareas, lambda { |a|	where(["city_id = ?", a]) }
	scope :doareaid, lambda { |ar| where(["name = ?", ar]) }
end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :areas
	scope :sort, lambda {order('position ASC')}
	scope :loid, lambda { |a| where(["name = ?", a]) }
end

app/models/priest_user.rb
class PriestUser < ActiveRecord::Base
	belongs_to :area

	scope :soting, lambda { order("created_at DESC")  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:position, :city_id, :name)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :position)
    end
end

app/controllers/priest_users_controller.rb
class PriestUsersController < ApplicationController
  before_action :set_priest_user, only: [:show, :edit, :update, :destroy]

  # GET /priest_users
  # GET /priest_users.json
  def index
    # @priest_users = PriestUser.all
    area = Area.doareaid(params['area'].to_s)
    religion = params['religion'].to_s
    area.each do |ar|
      @areaid = ar.id
    end
    @results = PriestUser.where(area_id: @areaid,religion: religion).soting
  end

  # GET /priest_users/1
  # GET /priest_users/1.json
  def show
  end

  # GET /priest_users/new
  def new
    @priest_user = PriestUser.new
  end

  # GET /priest_users/1/edit
  def edit
  end

  # POST /priest_users
  # POST /priest_users.json
  def create
    @priest_user = PriestUser.new(priest_user_params)

    respond_to do |format|
      if @priest_user.save
        format.html { redirect_to @priest_user, notice: 'Priest user was successfully created.' }
        format.json { render :show, status: :created, location: @priest_user }
      else
        format.html { render :new }
        format.json { render json: @priest_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /priest_users/1
  # PATCH/PUT /priest_users/1.json
  def update
    respond_to do |format|
      if @priest_user.update(priest_user_params)
        format.html { redirect_to @priest_user, notice: 'Priest user was successfully updated.' }
        format.json { render :show, status: :ok, location: @priest_user }
      else
        format.html { render :edit }
        format.json { render json: @priest_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priest_users/1
  # DELETE /priest_users/1.json
  def destroy
    @priest_user.destroy
    respond_to do |format|
      format.html { redirect_to priest_users_url, notice: 'Priest user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_priest_user
      @priest_user = PriestUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def priest_user_params
      params.require(:priest_user).permit(:area_id, :circles, :name, :religion, :phone, :brief, :description, :icon)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@lists = City.sort
  	
  end
  
  def ada
  lists = City.loid(params['name'].to_s)

  	lists.each do |list|
  		a = list.id
  		@areaz = Area.cityareas(a);
 	  end

    respond_to do |format|
      format.js
    end 

  end

  def search
  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/priest_users_helper.rb
module PriestUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/areas/_form.html.erb
<%= form_for(@area) do |f| %>
  <% if @area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% @area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.number_field :city_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Areas</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>City</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.position %></td>
        <td><%= area.city_id %></td>
        <td><%= area.name %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @area.position %>
</p>

<p>
  <strong>City:</strong>
  <%= @area.city_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @area.name %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.position %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @city.position %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_foot.html.erb
<div class="row foot">
<div class="col-md-2"></div>
	<div class="col-md-5">
	<%= image_tag('title.png', class: "foot-img") %>
		<p style="color:#7D919B;margin-top:2%;text-shadow: 0 0 0 #C09A67,0 0 0 #E8837E;">
			Get all at one place, we deal in bookings of Preists <br />
			for religious ceremonies or wedding plus Banquets,<br /> 
			Hotels, Tent vendors, Catering and more+..  
		</p>
	</div>
	<div class="col-md-1"></div>
	<div class="col-md-1">
		<ul><p style="color:#3C5460;font-weight:bold;">About</p>
		<li class="leee">Something</li>
		<li class="leee">Ptani</li>
		<li class="leee">KuchBhi</li>
		<li class="leee">Aive</li>
		</ul>
	</div>
	<div class="col-md-1">
		<ul><p style="color:#3C5460;font-weight:bold;">Products</p>
		<li class="leee">Something</li>
		<li class="leee">Ptani</li>
		<li class="leee">KuchBhi</li>
		<li class="leee">Aive</li>
		<li class="leee">Ekoradd</li>
		<li class="leee">Blabla</li>
		</ul>
	</div>
	<div class="col-md-1">
			<ul><p style="color:#3C5460;font-weight:bold;">Other</p>
		<li class="leee">KuchBhi</li>
		<li class="leee">Aive</li>
		<li class="leee">Blabla</li>
		</ul>
	</div>
	<div class="col-md-1"></div>
</div> 
<br /> <p style="font-size:10px;text-align:center;">&copy;2015 CodeDis. All Rights Reserved _ <a href="https://www.codedis.com"> www.codedis.com</a></p>

app/views/partials/_search1.html.erb
	<div class="city-search-form">
	<!-- 	<p class="pe">Select City</p><input type="text" id="a">
		
		<ul class="select">
		<%# for list in @lists%>
		<li class="pee noselect"><%=list.name%></li>
		<%#end%>
		</ul>
		<div class="bun noselect">Search</div> -->
		<%=form_for(:city, url: {action: @t}) do |f|%>
		<p class="pe">Select City</p>
		<%=f.text_field(:name, id: "a")%>
		<%=submit_tag ("Search")%>
		<ul class="select">
		<% for list in @lists%>
		<li class="pee noselect"><%=list.name%></li>
		<%end%>
		</ul>
		
	</div>

app/views/partials/_side.html.erb
<div class="sideBar pull-left noselect">
	<div class="logoHolder"><%= image_tag('logo.png', class: "logo") %></div>
	<div class="sideMenu">
		<p class="m1"><span class="glyphicon glyphicon-list-alt"></span><br />SomeMenu1</p>
		<p class="m2"><span class="glyphicon glyphicon-blackboard"></span><br />SomeMenu2</p>
		<p class="m3"><span class="glyphicon glyphicon-picture"></span><br />SomeMenu3</p>
		<p class="m4"><span class="glyphicon glyphicon-road"></span><br />SomeMenu4</p>
		<p class="m5"><span class="glyphicon glyphicon-off"></span><br />SomeMenu5</p>
	</div>
</div>

app/views/priest_users/_form.html.erb
<%= form_for(@priest_user) do |f| %>
  <% if @priest_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@priest_user.errors.count, "error") %> prohibited this priest_user from being saved:</h2>

      <ul>
      <% @priest_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :area_id %><br>
    <%= f.number_field :area_id %>
  </div>
  <div class="field">
    <%= f.label :circles %><br>
    <%= f.text_field :circles %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :religion %><br>
    <%= f.text_field :religion %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :brief %><br>
    <%= f.text_area :brief %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :icon %><br>
    <%= f.text_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/priest_users/edit.html.erb
<h1>Editing Priest User</h1>

<%= render 'form' %>

<%= link_to 'Show', @priest_user %> |
<%= link_to 'Back', priest_users_path %>

app/views/priest_users/index.html.erb
<%=render 'partials/side'%>
<div class="result-container">
  <p id="notice" style="position:absolute;"><%= notice %></p>

<!--==============LISTING PRIEST HEADER DIV===================-->
<div class="listing-priests">
<h1>Results for Priests.. <span class="glyphicon glyphicon-search"></span></h1>
</div>



    <% @results.each do |priest_user| %>
      <div class="row repeat">

      <div class="col-md-2 name"><%= priest_user.name %></div>
      <div class="col-md-1"><%= image_tag('default.png', class: "img-circle thumbnail dicon") %></div>
      <div class="col-md-1"><%= priest_user.religion %></div>

      <div class="col-md-2"><%= priest_user.circles %></div>
      <div class="col-md-1">+91-<%= priest_user.phone %></div>
      <div class="col-md-4"><%= priest_user.brief %></div>

      <div class="col-md-1"><%= link_to 'ViewProfile', priest_user %></div>
        <%#= link_to 'Edit', edit_priest_user_path(priest_user) %>
        <%#= link_to 'Destroy', priest_user, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div><br />
    <% end %>


<br><br>

<%= link_to 'Sign Up as a Priest', new_priest_user_path %>
</div>
<%=render 'partials/foot'%>

app/views/priest_users/new.html.erb
<h1>New Priest User</h1>

<%= render 'form' %>

<%= link_to 'Back', priest_users_path %>

app/views/priest_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @priest_user.area_id %>
</p>

<p>
  <strong>Circles:</strong>
  <%= @priest_user.circles %>
</p>

<p>
  <strong>Name:</strong>
  <%= @priest_user.name %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @priest_user.religion %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @priest_user.phone %>
</p>

<p>
  <strong>Brief:</strong>
  <%= @priest_user.brief %>
</p>

<p>
  <strong>Description:</strong>
  <%= @priest_user.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @priest_user.icon %>
</p>

<%= link_to 'Edit', edit_priest_user_path(@priest_user) %> |
<%= link_to 'Back', priest_users_path %>

app/views/welcome/_par1.html.erb
<%=form_tag({controller: "welcome", action: "ada"}, method: "get", class: "city-search-form", remote: true) do%>
 <p class="pe">Select City</p> 
<input type="text" name="name" class="a" autocomplete="off" >
<%=submit_tag('Search',class: "bun noselect")%>
<%end%>	
<ul class="select">
	<%@lists.each do |list| %>
		<li class="pee noselect"><%=list.name%></li>
	<%end%>
</ul>

app/views/welcome/_par2.html.erb
<div class="pilu"><div class="foo">

<form action="/priest_users" method="get" class="pharm">
<p class="par noselect">Select Area</p> 
<input type="text" name="area" class="ar" autocomplete="off" >

<p class="pre noselect">Select Religion</p> 
<input type="text" name="religion" class="re" autocomplete="off" >

<input type="text" name="ocassion" class="oc" autocomplete="off" >

<input type="submit" name="commit" value="Priests" class="pun noselect">
</form>
<ul class="arselect">
	<%@areaz.each do |area| %>
		<li class="pee noselect"><%=area.name%></li>
	<%end%>
</ul>
<ul class="reselect">
	<li class="repee noselect">Hindu</li><li class="repee noselect">Muslim</li>
	<li class="repee noselect">Sikh</li><li class="repee noselect">Christian</li>
	<li class="repee noselect">Buddhist</li><li class="repee noselect">Zoroastrin</li>
</ul>
<ul class="ocselect">
	<li class="ocpee noselect">Small Ceremony</li><li class="ocpee noselect">Wedding</li>
</ul>
<p class="poc noselect">Select Ocassion</p>
</div></div>

<%=javascript_tag do%>
$('.foo').hide();
$('.arselect').hide();
        $(".ar").click(function(){
        $(".arselect").slideToggle(300);
        $(".par").animate({top:"-48px"},80,function(){
                $(".par").animate({left:"-28px"},100,function(){
                    $(".par").css({"color":"#00A78B"});
                    });
                });
        });
        $(".par").click(function(){
        $(".arselect").slideDown(300);
        $(".par").animate({top:"-48px"},80,function(){
                $(".par").animate({left:"-28px"},100,function(){
                    $(".par").css({"color":"#00A78B"});
                    });
                });
        });
        $('.pee').click(function(){
        var bal = $(this).text();
        $('.ar').val(bal);
        $(".arselect").slideUp(300);
            });





$('.reselect').hide();
        $(".re").click(function(){
        $(".reselect").slideToggle(300);
        $(".pre").animate({top:"222px"},80,function(){
                $(".pre").animate({left:"-10px"},100,function(){
                    $(".pre").css({"color":"#00A78B"});
                    });
                });
        });
        $(".pre").click(function(){
        $(".reselect").slideDown(300);
        $(".pre").animate({top:"222px"},80,function(){
                $(".pre").animate({left:"-10px"},100,function(){
                    $(".pre").css({"color":"#00A78B"});
                    });
                });
        });
        $('.repee').click(function(){
        var kal = $(this).text();
        $('.re').val(kal);
        $(".reselect").slideUp(300);
            }); 






$('.ocselect').hide();
        $(".oc").click(function(){
        $(".ocselect").slideToggle(300);
        $(".poc").animate({top:"222px"},80,function(){
                $(".poc").animate({left:"-10px"},100,function(){
                    $(".poc").css({"color":"#00A78B"});
                    });
                });
        });
        $(".poc").click(function(){
        $(".ocselect").slideDown(300);
        $(".poc").animate({top:"222px"},80,function(){
                $(".poc").animate({left:"-10px"},100,function(){
                    $(".poc").css({"color":"#00A78B"});
                    });
                });
        });
        $('.ocpee').click(function(){
        var pal = $(this).text();
        $('.oc').val(pal);
        $(".ocselect").slideUp(300);
            });


		
 <%end%>

app/views/welcome/ada.js.erb
$('.ilu').replaceWith("<%= j render 'par2' %>");
$('.foo').fadeIn(300);

app/views/welcome/index.html.erb
<div style="width:1370px;height:525px;background-image:url(<%=asset_path 'back.png'%>);position:fixed;margin-left:-10px;margin-top:40px" class="noselect">
			<p
			style="position:absolute;text-shadow:3px 3px 10px #848FC1;font-family:helvetica, ubuntu;
			margin-left:10%;margin-top:6%;color:#ffffff;text-align:center;letter-spacing:4px;
			font-size:32px;"
			>Find a Priest just select your city your area and religion<br /> to filter down the results.</p>
			<div class="ilu"><%=render 'par1'%></div>			
</div>

<!--IDHAR -->